IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'InsureesAcademicHistory')
BEGIN 
	DROP TABLE dbo.InsureesAcademicHistory
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'InsureesNextPaymentAndBalanceInformation')
BEGIN 
	DROP TABLE dbo.InsureesNextPaymentAndBalanceInformation
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'InsureesPaymentHistory')
BEGIN 
	DROP TABLE dbo.InsureesPaymentHistory
END


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'InsureesPremiumCalculationDetails')
BEGIN 
	DROP TABLE dbo.InsureesPremiumCalculationDetails
END


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CollegeMajor')
BEGIN 
	DROP TABLE dbo.CollegeMajor
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CollegeDetail')
BEGIN 
	DROP TABLE dbo.CollegeDetail
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CollegeType')
BEGIN 
	DROP TABLE dbo.CollegeType
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CollegeAcademicTermType')
BEGIN 
	DROP TABLE dbo.CollegeAcademicTermType
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'InsureesAccountData')
BEGIN 
	DROP TABLE cust.InsureesAccountData
END