sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\cust.InsureesAccountData.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.ClaimAccountEntry.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.ClaimDocumentEntry.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.ClaimOptionEntry.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.ClaimPaymentEntry.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.ClaimStatusEntry.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.ClaimStatusType.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.CollegeAcademicTermType.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.CollegeDetail.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.CollegeMajor.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.CollegeType.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.FileVerificationStatusType.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InstitutionsAccountData.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InstitutionsInsureeList.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InstitutionsNextPaymentAndBalanceInformation.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InstitutionsNotificationHistoryEntry.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InstitutionsPaymentHistoryEntry.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesAcademicHistory.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesEnrollmentVerificationDetails.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesGraduationVerificationDetails.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesMajorMinorDetails.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesNextPaymentAndBalanceInformation.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesNotificationHistoryEntry.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesPaymentHistoryEntry.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesPremiumCalculationDetails.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesPremiumCalculationDetailsSet.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.InsureesPremiumCalculationOptionDetails.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.NotificationType.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.OptionType.Table.sql" >> "CreateTable.txt
sqlcmd -S edusafe.database.windows.net  -d EdusafeServicingDB -U EduSafeAdmin -P Master123 -i "1. Tables\dbo.PaymentStatusType.Table.sql" >> "CreateTable.txt
