EXEC cust.SP_InsertEmails 	1,'Matthew.Moore@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	2,'Sharon.Paesachov@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	3,'Anomandaris.Dragnipurake@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	4,'Butt.McPoopypants@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	5,'Trull.Sengar@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	6,'Paul.Atreides@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	7,'Karsa.Orlong@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	8,'Whiskey.Jack@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	9,'Fiddler.Strings@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	10,'Clark.Kent@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	11,'Bruce.Wayne@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	12,'Dassem.Ultor@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	13,'Onos.T''oolan@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	14,'Kalam.Mekhar@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	15,'Eye.Youpee@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	16,'Elephant.Shoe@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	17,'Kurt.Vonnegut@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	18,'Muad.Dib@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	19,'Mario.Luigi@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	20,'Princess.Peach@soWhatWhoCares.com'
EXEC cust.SP_InsertEmails 	21,'King .Koopa@soWhatWhoCares.com'

EXEC cust.SP_InsertEmails 	3,'Anomandaris.Dragnipurake@malazan.awesome'
EXEC cust.SP_InsertEmails 	4,'Butt.McPoopypants@poopooville.poopoo'
EXEC cust.SP_InsertEmails 	5,'Trull.Sengar@malazan.awesome'
