EXEC cust.SP_InsertEmails 	1,'Matthew.Moore@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	1,'Matthew.Moore@Edusafe.com'	,0
EXEC cust.SP_InsertEmails 	1,'Matthew.Moore@gmail.com'	,0
EXEC cust.SP_InsertEmails 	2,'Sharon.Paesachov@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	2,'Sharon.Paesachov@EduSafe.com'	,0
EXEC cust.SP_InsertEmails 	2,'Sharon.Paesachov@gmail.com'	,0
EXEC cust.SP_InsertEmails 	3,'Anomandaris.Dragnipurake@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	3,'Anomandaris.Dragnipurake@malazan.awesome'	,0
EXEC cust.SP_InsertEmails 	4,'Butt.McPoopypants@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	4,'Butt.McPoopypants@poopooville.poopoo'	,0
EXEC cust.SP_InsertEmails 	5,'Trull.Sengar@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	5,'Trull.Sengar@malazan.awesome'	,0
EXEC cust.SP_InsertEmails 	6,'Paul.Atreides@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	7,'Karsa.Orlong@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	8,'Whiskey.Jack@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	9,'Fiddler.Strings@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	10,'Clark.Kent@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	11,'Bruce.Wayne@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	12,'Dassem.Ultor@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	13,'Onos.T''oolan@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	14,'Kalam.Mekhar@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	15,'Eye.Youpee@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	16,'Elephant.Shoe@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	17,'Kurt.Vonnegut@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	18,'Muad.Dib@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	19,'Mario.Luigi@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	20,'Princess.Peach@soWhatWhoCares.com'	,1
EXEC cust.SP_InsertEmails 	21,'King .Koopa@soWhatWhoCares.com'	,1
