SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TableNameHere')
	BEGIN

		CREATE TABLE dbo.TableNameHere
		(
			Id int IDENTITY(1,1)
			, CreatedOn datetime null
			, CreatedBy varchar(25) 
			CONSTRAINT PK_TableNameHere PRIMARY KEY CLUSTERED (Id)
		)
	
	END